# This is a generated file. Not intended for manual editing.
services:
  repready:
    build:
      context: "/Users/codycass/RiderProjects/RepReady"
      dockerfile: "RepReady/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57401"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net10.0/RepReady.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "repready:dev"
    ports:
    - "127.0.0.1:57001:57000"
    - "127.0.0.1:57201:57200"
    - "127.0.0.1:57401:57401"
    volumes:
    - "/Users/codycass/RiderProjects/RepReady/RepReady:/app:rw"
    - "/Users/codycass/RiderProjects/RepReady:/src:rw"
    - "/Users/codycass/.nuget/packages:/root/.nuget/packages"
    - "/Users/codycass/.local/share/JetBrains/RiderRemoteDebugger/2025.3.0.4/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/codycass/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2025_12_18_06_38_06:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
