# This is a generated file. Not intended for manual editing.
services:
  repready:
    build:
      context: "/Users/codycass/RiderProjects/RepReady"
      dockerfile: "RepReady/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net10.0/RepReady.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net10.0/RepReady.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "repready:dev"
    ports: []
    volumes:
    - "/Users/codycass/RiderProjects/RepReady/RepReady:/app:rw"
    - "/Users/codycass/RiderProjects/RepReady:/src:rw"
    - "/Users/codycass/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app"
